function(parse_version PROJECT_MAJOR_VERSION PROJECT_MINOR_VERSION PROJECT_PATCH_VERSION)
  cmake_parse_arguments("arg" "" "PROJECT_VERSION" "" ${ARGN})

  if(NOT arg_PROJECT_VERSION)
    message(FATAL_ERROR "[${PROJECT_NAME}][parse_version] Missing required argument: PROJECT_VERSION")
  endif()

  string(REGEX MATCH "[1-9]+\.[0-9]+\.[0-9]+" IS_MATCHED ${arg_PROJECT_VERSION})
  if(NOT IS_MATCHED)
    message(
      FATAL_ERROR
        "[${PROJECT_NAME}][parse_version] PROJECT_VERSION does not matches regex expression: [1-9]+\.[0-9]+\.[0-9]+"
    )
  endif()

  block(SCOPE_FOR VARIABLES)
  string(FIND ${arg_PROJECT_VERSION} "." PROJECT_MAJOR_PIVOT_POS)
  string(SUBSTRING ${arg_PROJECT_VERSION} 0 ${PROJECT_MAJOR_PIVOT_POS} PROJECT_MAJOR_VERSION_RESULT)

  string(FIND ${arg_PROJECT_VERSION} "." PROJECT_PATCH_PIVOT_POS REVERSE)
  math(EXPR PROJECT_PATCH_VERSION_BEGIN_POS "${PROJECT_PATCH_PIVOT_POS} + 1")
  string(SUBSTRING ${arg_PROJECT_VERSION} ${PROJECT_PATCH_VERSION_BEGIN_POS} -1 PROJECT_PATCH_VERSION_RESULT)

  math(EXPR PROJECT_MINOR_VERSION_BEGIN_POS "${PROJECT_MAJOR_PIVOT_POS} + 1")
  math(EXPR PROJECT_MINOR_VERSION_LENGTH "${PROJECT_PATCH_PIVOT_POS} - ${PROJECT_MINOR_VERSION_BEGIN_POS}")
  string(SUBSTRING ${arg_PROJECT_VERSION} ${PROJECT_MINOR_VERSION_BEGIN_POS} ${PROJECT_MINOR_VERSION_LENGTH}
                   PROJECT_MINOR_VERSION_RESULT
  )

  set(${PROJECT_MAJOR_VERSION} ${PROJECT_MAJOR_VERSION_RESULT})
  set(${PROJECT_MINOR_VERSION} ${PROJECT_MINOR_VERSION_RESULT})
  set(${PROJECT_PATCH_VERSION} ${PROJECT_PATCH_VERSION_RESULT})

  return(PROPAGATE ${PROJECT_MAJOR_VERSION} ${PROJECT_MINOR_VERSION} ${PROJECT_PATCH_VERSION})
  endblock()
endfunction()
